export const siteConfig = {
  name: "Omar Atri Portfolio",
  authorName: "Omar Atri",
  username: "omaratri",
  description:
    "Omar Atri's developer portfolio showcasing skills, experience, and projects. Built with Next.js and available as an open-source template.",
  url: "https://omaratri.com",
  links: {
    github: "https://github.com/AtriOmar",
  },
  ogImage: "https://omaratri.com/logo_square.jpg",
  iconIco: "https://omaratri.com/logo.jpg",
  logoIcon: "https://omaratri.com/logo.jpg",
  keywords: [
    "Omar Atri",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
